import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "@/components/Home/AppContext";
import EventContextProvider from "@/components/Home/EventContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><AppContextProvider><EventContextProvider>{children}</EventContextProvider></AppContextProvider></body>
    </html>
  );
}
